EMBEDDING_FILE = 'embeddings.pkl'

SIMILARITY_THRESHOLD = 0.5

EMPLOYEE_PHOTOS_DIR = './photos'

ARC_FACE_MODEL = 'ArcFace'

FRAME_COUNT = 5

CONSECUTIVE_REQUIRED = 3

VAR_LAPLACIAN_MIN = 100.0

MIN_FACE_RATIO = 0.05

BRIGHTNESS_MIN = 60
BRIGHTNESS_MAX = 200

RECOG_TIME_LIMIT_SECS = 10

EARLY_ACCEPT_MARGIN = 0.05

PREFERRED_CAMERA_INDEX = 0

PREFERRED_CAMERA_BACKEND = 'CAP_ANY'
